### 1. 用户注册
POST http://localhost:8080/user/register
    ?username=testuser
    &password=test123

### 2. 用户登录
POST http://localhost:8080/user/login
    ?username=testuser
    &password=test123

> {% client.global.set("auther_token", response.body.data) %}

### 3. 更新用户头像 (使用你提供的图片URL)
PATCH http://localhost:8080/user/updateAvatar
    ?avatarUrl=https://aircraft-carrier.github.io/images/avatar.jpg
Authorization: {{auther_token}}

### 4. 创建聊天会话
POST http://localhost:8080/api/chat/sessions
    ?sessionName=hello
Authorization: {{auther_token}}

### 5. 发送消息
POST http://localhost:8080/api/chat/messages
    ?sessionId=1
Authorization: {{auther_token}}
Content-Type: application/json

{
  "content": "你好，这是一个测试"
}

### 6. 获取消息历史
GET http://localhost:8080/api/chat/messages
    ?sessionId=1
Authorization: {{auther_token}}


### 7. 更新密码
PATCH http://localhost:8080/user/updatePwd
Authorization: {{auther_token}}
Content-Type: application/json

{
  "old_pwd": "test123",
  "new_pwd": "newpassword123",
  "re_pwd": "newpassword123"
}

### 8. 创建文件夹
POST http://localhost:8080/api/files/folders
    ?folderName=testFolder
Authorization: {{auther_token}}

### 9. 创建二级文件夹
POST http://localhost:8080/api/files/folders
    ?folderName=testFolder2
    &parentId=3
Authorization: {{auther_token}}

### 10. 上传文件
POST http://localhost:8080/api/files/upload?folderId=3
Content-Type: multipart/form-data;boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{auther_token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="upload_test.txt"
Content-Type: text/plain

< D:\Dataset\Go_ZTC\upload_test.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 11. 查看根目录下的文件夹列表
GET http://localhost:8080/api/files/folders
Authorization: {{auther_token}}

### 12. 查看指定文件夹下的文件夹列表
GET http://localhost:8080/api/files/folders?parentId=3
Authorization: {{auther_token}}

### 13. 查看根目录下的文件列表
GET http://localhost:8080/api/files/files
Authorization: {{auther_token}}

### 14. 查看指定文件夹下的文件列表
GET http://localhost:8080/api/files/files?folderId=3
Authorization: {{auther_token}}

### 15. 递归查看根文件夹下的所有文件夹和文件
GET http://localhost:8080/api/files/tree
Authorization: {{auther_token}}

### 16. 删除文件
DELETE http://localhost:8080/api/files/files/6
Authorization: {{auther_token}}

### 17. 删除文件夹
DELETE http://localhost:8080/api/files/folders/6
Authorization: {{auther_token}}