spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/go_ztc
    username: root
    password: TAn20050308
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  storage:
    root: /files

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
server:
  port: 8080
  tomcat:
    connection-timeout: 20000ms  # 设置连接超时为 20 秒
    max-swallow-size: -1

okhttp:
  connect-timeout: 30
  read-timeout: 30
  write-timeout: 30
  max-idle-connections: 200
  keep-alive-duration: 300

# Flask RAG后端配置
rag:
  api:
    url: "http://localhost:5000"
    timeout: 30
